// Code generated by go-swagger; DO NOT EDIT.

// Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package api_individual

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wso2/micro-gw/pkg/api/models"
)

// PutAPIOKCode is the HTTP code returned for type PutAPIOK
const PutAPIOKCode int = 200

/*PutAPIOK Successful.
API deployed or updated Successfully.


swagger:response putApiOK
*/
type PutAPIOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeployResponse `json:"body,omitempty"`
}

// NewPutAPIOK creates PutAPIOK with default headers values
func NewPutAPIOK() *PutAPIOK {

	return &PutAPIOK{}
}

// WithPayload adds the payload to the put Api o k response
func (o *PutAPIOK) WithPayload(payload *models.DeployResponse) *PutAPIOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put Api o k response
func (o *PutAPIOK) SetPayload(payload *models.DeployResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAPIOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAPIForbiddenCode is the HTTP code returned for type PutAPIForbidden
const PutAPIForbiddenCode int = 403

/*PutAPIForbidden Forbidden.
Not Authorized to deploy or update.


swagger:response putApiForbidden
*/
type PutAPIForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAPIForbidden creates PutAPIForbidden with default headers values
func NewPutAPIForbidden() *PutAPIForbidden {

	return &PutAPIForbidden{}
}

// WithPayload adds the payload to the put Api forbidden response
func (o *PutAPIForbidden) WithPayload(payload *models.Error) *PutAPIForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put Api forbidden response
func (o *PutAPIForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAPIForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAPINotFoundCode is the HTTP code returned for type PutAPINotFound
const PutAPINotFoundCode int = 404

/*PutAPINotFound Not Found.
Requested API to update not found (when overwrite parameter is included).


swagger:response putApiNotFound
*/
type PutAPINotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAPINotFound creates PutAPINotFound with default headers values
func NewPutAPINotFound() *PutAPINotFound {

	return &PutAPINotFound{}
}

// WithPayload adds the payload to the put Api not found response
func (o *PutAPINotFound) WithPayload(payload *models.Error) *PutAPINotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put Api not found response
func (o *PutAPINotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAPINotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAPIInternalServerErrorCode is the HTTP code returned for type PutAPIInternalServerError
const PutAPIInternalServerErrorCode int = 500

/*PutAPIInternalServerError Internal Server Error.

swagger:response putApiInternalServerError
*/
type PutAPIInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAPIInternalServerError creates PutAPIInternalServerError with default headers values
func NewPutAPIInternalServerError() *PutAPIInternalServerError {

	return &PutAPIInternalServerError{}
}

// WithPayload adds the payload to the put Api internal server error response
func (o *PutAPIInternalServerError) WithPayload(payload *models.Error) *PutAPIInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put Api internal server error response
func (o *PutAPIInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAPIInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
