// Code generated by go-swagger; DO NOT EDIT.
// Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Package restserver WSO2 API Microgateway - Adapter
//
//  This document specifies a **RESTful API** for WSO2 **API Microgateway** - Adapter.
//
//  Schemes:
//    https
//  Host: apis.wso2.com
//  BasePath: /api/mgw/adapter/0.1
//  Version: v1.2
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: WSO2<architecture@wso2.com> http://wso2.com/products/api-manager/
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package restserver
