// Code generated by go-swagger; DO NOT EDIT.

// Package restserver WSO2 API Microgateway - Adapter
//
//  This document specifies a **RESTful API** for WSO2 **API Microgateway** - Adapter.
//
//  Schemes:
//    https
//  Host: apis.wso2.com
//  BasePath: /api/mgw/adapter/0.1
//  Version: v1.2
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: WSO2<architecture@wso2.com> http://wso2.com/products/api-manager/
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//
//  Produces:
//    - application/json
//
// swagger:meta
package restserver
