//  Copyright (c) 2022, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
//
//  WSO2 Inc. licenses this file to you under the Apache License,
//  Version 2.0 (the "License"); you may not use this file except
//  in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing,
//  software distributed under the License is distributed on an
//  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//  KIND, either express or implied.  See the License for the
//  specific language governing permissions and limitations
//  under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: wso2/discovery/api/mocked_api_config.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MockedApiConfig holds configurations defined for a mocked API operation result
type MockedApiConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	In        string                  `protobuf:"bytes,1,opt,name=in,proto3" json:"in,omitempty"`
	Name      string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Responses []*MockedResponseConfig `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *MockedApiConfig) Reset() {
	*x = MockedApiConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wso2_discovery_api_mocked_api_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MockedApiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockedApiConfig) ProtoMessage() {}

func (x *MockedApiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_discovery_api_mocked_api_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockedApiConfig.ProtoReflect.Descriptor instead.
func (*MockedApiConfig) Descriptor() ([]byte, []int) {
	return file_wso2_discovery_api_mocked_api_config_proto_rawDescGZIP(), []int{0}
}

func (x *MockedApiConfig) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *MockedApiConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MockedApiConfig) GetResponses() []*MockedResponseConfig {
	if x != nil {
		return x.Responses
	}
	return nil
}

// MockedResponseConfig hold response configurations for the mocked API implementations
type MockedResponseConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   string                `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Headers []*MockedHeaderConfig `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	Code    int32                 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Payload *MockedPayloadConfig  `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *MockedResponseConfig) Reset() {
	*x = MockedResponseConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wso2_discovery_api_mocked_api_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MockedResponseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockedResponseConfig) ProtoMessage() {}

func (x *MockedResponseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_discovery_api_mocked_api_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockedResponseConfig.ProtoReflect.Descriptor instead.
func (*MockedResponseConfig) Descriptor() ([]byte, []int) {
	return file_wso2_discovery_api_mocked_api_config_proto_rawDescGZIP(), []int{1}
}

func (x *MockedResponseConfig) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MockedResponseConfig) GetHeaders() []*MockedHeaderConfig {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *MockedResponseConfig) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MockedResponseConfig) GetPayload() *MockedPayloadConfig {
	if x != nil {
		return x.Payload
	}
	return nil
}

// MockedHeaderConfig holds header configs in mocked API implementations
type MockedHeaderConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *MockedHeaderConfig) Reset() {
	*x = MockedHeaderConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wso2_discovery_api_mocked_api_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MockedHeaderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockedHeaderConfig) ProtoMessage() {}

func (x *MockedHeaderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_discovery_api_mocked_api_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockedHeaderConfig.ProtoReflect.Descriptor instead.
func (*MockedHeaderConfig) Descriptor() ([]byte, []int) {
	return file_wso2_discovery_api_mocked_api_config_proto_rawDescGZIP(), []int{2}
}

func (x *MockedHeaderConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MockedHeaderConfig) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// MockedPayloadConfig holds payload configs in mocked API implementations
type MockedPayloadConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationJSON string `protobuf:"bytes,1,opt,name=applicationJSON,proto3" json:"applicationJSON,omitempty"`
	ApplicationXML  string `protobuf:"bytes,2,opt,name=applicationXML,proto3" json:"applicationXML,omitempty"`
}

func (x *MockedPayloadConfig) Reset() {
	*x = MockedPayloadConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wso2_discovery_api_mocked_api_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MockedPayloadConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockedPayloadConfig) ProtoMessage() {}

func (x *MockedPayloadConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wso2_discovery_api_mocked_api_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockedPayloadConfig.ProtoReflect.Descriptor instead.
func (*MockedPayloadConfig) Descriptor() ([]byte, []int) {
	return file_wso2_discovery_api_mocked_api_config_proto_rawDescGZIP(), []int{3}
}

func (x *MockedPayloadConfig) GetApplicationJSON() string {
	if x != nil {
		return x.ApplicationJSON
	}
	return ""
}

func (x *MockedPayloadConfig) GetApplicationXML() string {
	if x != nil {
		return x.ApplicationXML
	}
	return ""
}

var File_wso2_discovery_api_mocked_api_config_proto protoreflect.FileDescriptor

var file_wso2_discovery_api_mocked_api_config_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x77, 0x73, 0x6f, 0x32, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x70, 0x69, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x77, 0x73,
	0x6f, 0x32, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x61, 0x70, 0x69,
	0x22, 0x7d, 0x0a, 0x0f, 0x4d, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x77, 0x73, 0x6f,
	0x32, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22,
	0xc5, 0x01, 0x0a, 0x14, 0x4d, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x40,
	0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x77, 0x73, 0x6f, 0x32, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x77, 0x73, 0x6f, 0x32, 0x2e, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3e, 0x0a, 0x12, 0x4d, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x67, 0x0a, 0x13, 0x4d, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x28,
	0x0a, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x53, 0x4f,
	0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4a, 0x53, 0x4f, 0x4e, 0x12, 0x26, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x4d, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x4d, 0x4c,
	0x42, 0x7e, 0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2e, 0x77, 0x73, 0x6f, 0x32, 0x2e, 0x63, 0x68, 0x6f,
	0x72, 0x65, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x42, 0x14, 0x4d, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x41, 0x70, 0x69, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e,
	0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x2d, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x2f, 0x77, 0x73, 0x6f, 0x32, 0x2f, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wso2_discovery_api_mocked_api_config_proto_rawDescOnce sync.Once
	file_wso2_discovery_api_mocked_api_config_proto_rawDescData = file_wso2_discovery_api_mocked_api_config_proto_rawDesc
)

func file_wso2_discovery_api_mocked_api_config_proto_rawDescGZIP() []byte {
	file_wso2_discovery_api_mocked_api_config_proto_rawDescOnce.Do(func() {
		file_wso2_discovery_api_mocked_api_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_wso2_discovery_api_mocked_api_config_proto_rawDescData)
	})
	return file_wso2_discovery_api_mocked_api_config_proto_rawDescData
}

var file_wso2_discovery_api_mocked_api_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wso2_discovery_api_mocked_api_config_proto_goTypes = []interface{}{
	(*MockedApiConfig)(nil),      // 0: wso2.discovery.api.MockedApiConfig
	(*MockedResponseConfig)(nil), // 1: wso2.discovery.api.MockedResponseConfig
	(*MockedHeaderConfig)(nil),   // 2: wso2.discovery.api.MockedHeaderConfig
	(*MockedPayloadConfig)(nil),  // 3: wso2.discovery.api.MockedPayloadConfig
}
var file_wso2_discovery_api_mocked_api_config_proto_depIdxs = []int32{
	1, // 0: wso2.discovery.api.MockedApiConfig.responses:type_name -> wso2.discovery.api.MockedResponseConfig
	2, // 1: wso2.discovery.api.MockedResponseConfig.headers:type_name -> wso2.discovery.api.MockedHeaderConfig
	3, // 2: wso2.discovery.api.MockedResponseConfig.payload:type_name -> wso2.discovery.api.MockedPayloadConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wso2_discovery_api_mocked_api_config_proto_init() }
func file_wso2_discovery_api_mocked_api_config_proto_init() {
	if File_wso2_discovery_api_mocked_api_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wso2_discovery_api_mocked_api_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MockedApiConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wso2_discovery_api_mocked_api_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MockedResponseConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wso2_discovery_api_mocked_api_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MockedHeaderConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wso2_discovery_api_mocked_api_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MockedPayloadConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wso2_discovery_api_mocked_api_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wso2_discovery_api_mocked_api_config_proto_goTypes,
		DependencyIndexes: file_wso2_discovery_api_mocked_api_config_proto_depIdxs,
		MessageInfos:      file_wso2_discovery_api_mocked_api_config_proto_msgTypes,
	}.Build()
	File_wso2_discovery_api_mocked_api_config_proto = out.File
	file_wso2_discovery_api_mocked_api_config_proto_rawDesc = nil
	file_wso2_discovery_api_mocked_api_config_proto_goTypes = nil
	file_wso2_discovery_api_mocked_api_config_proto_depIdxs = nil
}
