[adapter] 
[adapter.keystore]
  certPath = "/home/wso2/security/keystore/mg.pem"
  keyPath = "/home/wso2/security/keystore/mg.key"

[adapter.truststore]
  location = "/home/wso2/security/truststore"

[router]
  listenerPort = 9090
  securedListenerPort = 9095
  systemHost = "localhost"

[router.keystore]
  certPath = "/home/wso2/security/keystore/mg.pem"
  keyPath = "/home/wso2/security/keystore/mg.key"

[router.upstream]
[router.upstream.tls]
  trustedCertPath = "/etc/ssl/certs/ca-certificates.crt"
  verifyHostName = true
  disableSslVerification = false

[enforcer]
[enforcer.jwtIssuer]
  enabled = true
  issuer = "https://localhost:9095/testkey"

[enforcer.throttling]
  enableGlobalEventPublishing = true
  jmsConnectionProviderUrl = "amqp://admin:$env{tm_admin_pwd}@carbon/carbon?brokerlist='tcp://apim:5672'"
  [enforcer.throttling.publisher]
    username = "admin"
    password = "$env{tm_admin_pwd}"
    [[enforcer.throttling.publisher.urlGroup]]
      receiverURLs = ["tcp://apim:9611"]
      authURLs = ["ssl://apim:9711"]

[enforcer.security]
[[enforcer.security.tokenService]]
  name = "Resident Key Manager"
  issuer = "https://localhost:9443/oauth2/token"
  certificateAlias = "wso2carbon"
  jwksURL = ""
  validateSubscription = false
  consumerKeyClaim = "azp"
  certificateFilePath = "/home/wso2/security/truststore/wso2carbon.pem"

[[enforcer.security.tokenService]]
  name = "MGW"
  issuer = "https://localhost:9095/testkey"
  certificateAlias = "mgw"
  jwksURL = ""
  validateSubscription = false
  consumerKeyClaim = ""
  certificateFilePath = "/home/wso2/security/truststore/mg.pem"

[[enforcer.security.tokenService]]
  name = "APIM Publisher"
  issuer = "https://localhost:9443/publisher"
  certificateFilePath = "/home/wso2/security/truststore/wso2carbon.pem"

[controlPlane]
  enabled = true
  serviceUrl = "https://apim:9443/"
  username = "admin"
  password = "$env{cp_admin_pwd}"
  clientRegisterEndpoint = "https://apim:9443/client-registration/v0.17/register"
  tokenEndpoint = "https://apim:9443/oauth2/token"
  environmentLabels = ["Default"]
  skipSSLVerification = true
  [controlPlane.jmsConnectionParameters]
    eventListeningEndpoints = ["amqp://admin:$env{cp_admin_pwd}@apim:5672?retries='10'&connectdelay='30'"]

[analytics]
  enabled = false
