// Code generated by go-swagger; DO NOT EDIT.

package api_individual

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
)

// DeleteApisURL generates an URL for the delete apis operation
type DeleteApisURL struct {
	APIName      string
	Environments *string
	Version      string
	Vhost        *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteApisURL) WithBasePath(bp string) *DeleteApisURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteApisURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteApisURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/apis"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/mgw/adapter/0.1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	aPINameQ := o.APIName
	if aPINameQ != "" {
		qs.Set("apiName", aPINameQ)
	}

	var environmentsQ string
	if o.Environments != nil {
		environmentsQ = *o.Environments
	}
	if environmentsQ != "" {
		qs.Set("environments", environmentsQ)
	}

	versionQ := o.Version
	if versionQ != "" {
		qs.Set("version", versionQ)
	}

	var vhostQ string
	if o.Vhost != nil {
		vhostQ = *o.Vhost
	}
	if vhostQ != "" {
		qs.Set("vhost", vhostQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteApisURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteApisURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteApisURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteApisURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteApisURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteApisURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
