// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	v3 "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ApiDiscoveryServiceClient is the client API for ApiDiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiDiscoveryServiceClient interface {
	StreamApis(ctx context.Context, opts ...grpc.CallOption) (ApiDiscoveryService_StreamApisClient, error)
	FetchApis(ctx context.Context, in *v3.DiscoveryRequest, opts ...grpc.CallOption) (*v3.DiscoveryResponse, error)
}

type apiDiscoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiDiscoveryServiceClient(cc grpc.ClientConnInterface) ApiDiscoveryServiceClient {
	return &apiDiscoveryServiceClient{cc}
}

func (c *apiDiscoveryServiceClient) StreamApis(ctx context.Context, opts ...grpc.CallOption) (ApiDiscoveryService_StreamApisClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ApiDiscoveryService_serviceDesc.Streams[0], "/discovery.service.api.ApiDiscoveryService/StreamApis", opts...)
	if err != nil {
		return nil, err
	}
	x := &apiDiscoveryServiceStreamApisClient{stream}
	return x, nil
}

type ApiDiscoveryService_StreamApisClient interface {
	Send(*v3.DiscoveryRequest) error
	Recv() (*v3.DiscoveryResponse, error)
	grpc.ClientStream
}

type apiDiscoveryServiceStreamApisClient struct {
	grpc.ClientStream
}

func (x *apiDiscoveryServiceStreamApisClient) Send(m *v3.DiscoveryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *apiDiscoveryServiceStreamApisClient) Recv() (*v3.DiscoveryResponse, error) {
	m := new(v3.DiscoveryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiDiscoveryServiceClient) FetchApis(ctx context.Context, in *v3.DiscoveryRequest, opts ...grpc.CallOption) (*v3.DiscoveryResponse, error) {
	out := new(v3.DiscoveryResponse)
	err := c.cc.Invoke(ctx, "/discovery.service.api.ApiDiscoveryService/FetchApis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiDiscoveryServiceServer is the server API for ApiDiscoveryService service.
// All implementations must embed UnimplementedApiDiscoveryServiceServer
// for forward compatibility
type ApiDiscoveryServiceServer interface {
	StreamApis(ApiDiscoveryService_StreamApisServer) error
	FetchApis(context.Context, *v3.DiscoveryRequest) (*v3.DiscoveryResponse, error)
	mustEmbedUnimplementedApiDiscoveryServiceServer()
}

// UnimplementedApiDiscoveryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApiDiscoveryServiceServer struct {
}

func (UnimplementedApiDiscoveryServiceServer) StreamApis(ApiDiscoveryService_StreamApisServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamApis not implemented")
}
func (UnimplementedApiDiscoveryServiceServer) FetchApis(context.Context, *v3.DiscoveryRequest) (*v3.DiscoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchApis not implemented")
}
func (UnimplementedApiDiscoveryServiceServer) mustEmbedUnimplementedApiDiscoveryServiceServer() {}

// UnsafeApiDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiDiscoveryServiceServer will
// result in compilation errors.
type UnsafeApiDiscoveryServiceServer interface {
	mustEmbedUnimplementedApiDiscoveryServiceServer()
}

func RegisterApiDiscoveryServiceServer(s grpc.ServiceRegistrar, srv ApiDiscoveryServiceServer) {
	s.RegisterService(&_ApiDiscoveryService_serviceDesc, srv)
}

func _ApiDiscoveryService_StreamApis_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApiDiscoveryServiceServer).StreamApis(&apiDiscoveryServiceStreamApisServer{stream})
}

type ApiDiscoveryService_StreamApisServer interface {
	Send(*v3.DiscoveryResponse) error
	Recv() (*v3.DiscoveryRequest, error)
	grpc.ServerStream
}

type apiDiscoveryServiceStreamApisServer struct {
	grpc.ServerStream
}

func (x *apiDiscoveryServiceStreamApisServer) Send(m *v3.DiscoveryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *apiDiscoveryServiceStreamApisServer) Recv() (*v3.DiscoveryRequest, error) {
	m := new(v3.DiscoveryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ApiDiscoveryService_FetchApis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v3.DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiDiscoveryServiceServer).FetchApis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discovery.service.api.ApiDiscoveryService/FetchApis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiDiscoveryServiceServer).FetchApis(ctx, req.(*v3.DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiDiscoveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.service.api.ApiDiscoveryService",
	HandlerType: (*ApiDiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchApis",
			Handler:    _ApiDiscoveryService_FetchApis_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamApis",
			Handler:       _ApiDiscoveryService_StreamApis_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wso2/discovery/service/api/apids.proto",
}
