/*
 * Choreo-Connect Interceptor Service
 *
 * Interceptor Service
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequestHandlerRequestBody struct {
	RequestHeaders *map[string]string `json:"requestHeaders,omitempty"`

	RequestTrailers *map[string]string `json:"requestTrailers,omitempty"`

	RequestBody string `json:"requestBody,omitempty"`

	InvocationContext *InvocationContext `json:"invocationContext,omitempty"`
}
