{
 "title": "MicroGateway Performance",
 "description": "Moniter the performance of Microgateway",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": "label_values(service)" },
   { "name": "instance", "label": "instance", "query": "label_values(instance)" },
   { "name": "resource", "label": "resource", "query": "label_values(resource)" },
   { "name": "protocol", "label": "protocol", "query": "label_values(protocol)" },
   { "name": "http_method", "label": "http-method", "query": "label_values(http_method)" },
   { "name": "http_url", "label": "http-url", "query": "label_values(http_url)" },
   { "name": "peer_address", "label": "peer-address", "query": "label_values(peer_address)" },
   {
    "name": "http_client_action",
    "label": "http-client-action",
    "query": "label_values(ballerina_http_HttpClient_requests_total_value,action)"
   },
   {
    "name": "db_action",
    "label": "db-action",
    "query": "label_values(ballerinax_java_jdbc_JdbcClient_requests_total_value,action)"
   },
   {
    "name": "db_statement",
    "label": "db-statement",
    "query": "label_values(ballerinax_java_jdbc_JdbcClient_requests_total_value,db_statement)"
   },
   {
    "name": "db_instance",
    "label": "db-instance",
    "query": "label_values(ballerinax_java_jdbc_JdbcClient_requests_total_value,db_instance)"
   },
   { "name": "Method", "label": "Method", "query": "label_values(Method)" },
   { "name": "Category", "label": "Category", "query": "label_values(Category)" },
   { "name": "ServicePath(URL)", "label": "servicepath", "query": "label_values(ServicePath)" },
   { "name": "Bal_Service", "label": "service", "query": "label_values(Service)" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jvm_info{release=\"$release\"},kubernetes_pod_name)"
   },
   { "name": "release", "label": "release", "query": "label_values(release)" }
  ]
 },
 "panels": [
  {
   "title": "Instance  Up / Down",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{area=\"heap\",release=\"$release\"})*100) / sum(jvm_memory_bytes_max{area=\"heap\",release=\"$release\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 12, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{release=\"$release\"})"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad",
     "legendFormat": "Process_Cpu_Load , Instance: {{instance}}, Job: {{job}}"
    },
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad",
     "legendFormat": "System_Cpu_Load , Instance: {{instance}}, Job: {{job}}"
    }
   ]
  },
  {
   "title": "System Load Average( last 1m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage",
     "legendFormat": "System_Load_Average, Instance: {{instance}}, Job: {{job}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_bytes_Used, Area: {{area}}, Instance: {{instance}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_bytes_Max, Area: {{area}}, Instance: {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_bytes_Committed, Area: {{area}}, Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Non Heap Memory ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_bytes_Used, Area: {{area}}, Instance: {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",release=\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_bytes_Committed, Area: {{area}}, Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Threads_current, Instance: {{instance}}"
    },
    {
     "expr": "jvm_threads_daemon{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Threads_daemon, Instance: {{instance}}"
    },
    {
     "expr": "jvm_threads_deadlocked{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Threads_deadlocked, Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "GC  rate  [1 min]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "GC: {{gc}}, Instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Classes_Loaded, Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "GC count (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{release=~\"$release\",kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "GC: {{gc}}, Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes",
     "legendFormat": "Virtual_Memory_bytes, Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds",
     "legendFormat": "Process_Open_fds, Instance: {{instance}}"
    },
    {
     "expr": "process_max_fds",
     "legendFormat": "Process_Max_fds, Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"Metaspace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Max, Metaspace, Instance:{{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"Metaspace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Used, Metaspace, Instance:{{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"Metaspace\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Committed, Metaspace, Instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"Compressed Class Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Max, Compressed Class Space, Instance:{{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"Compressed Class Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Used, Compressed Class Space, Instance:{{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"Compressed Class Space\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Committed, Compressed Class Space, Instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{release=\"$release\", pool=\"Code Cache\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Max, Code Cache, Instance:{{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{release=\"$release\", pool=\"Code Cache\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Used, Code Cache, Instance:{{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{release=\"$release\", pool=\"Code Cache\",kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Memory_Pool_bytes_Committed, Code Cache, Instance:{{instance}}"
    }
   ]
  },
  {
   "title": "MicroGateway HTTP Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 }
  },
  {
   "title": "Requests / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(http_requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url!=\"/metrics\", http_url!=\"/jmxMetrics\",service=~\"$service\",resource=~\"$resource\"}[1m])-min_over_time(http_requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url!=\"/metrics\", http_url!=\"/jmxMetrics\",service=~\"$service\",resource=~\"$resource\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errors /  min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(ballerina_http_Caller_4XX_requests_total_value{instance=~\"$instance\"}[1m])-min_over_time(ballerina_http_Caller_4XX_requests_total_value{instance=~\"$instance\"}[1m])+max_over_time(ballerina_http_Caller_5XX_requests_total_value{instance=~\"$instance\"}[1m])-min_over_time(ballerina_http_Caller_5XX_requests_total_value{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Inprogress Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_inprogress_requests_value{instance=~\"$instance\",resource!=\"getMetrics\", resource!=\"balMetric\", resource!=\"jmxMetric\"})"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 59 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max_over_time(ballerina_http_Caller_4XX_requests_total_value{instance=~\"$instance\"}[1m]) - min_over_time(ballerina_http_Caller_4XX_requests_total_value{instance=~\"$instance\"}[1m])+max_over_time(ballerina_http_Caller_5XX_requests_total_value{instance=~\"$instance\"}[1m]) - min_over_time(ballerina_http_Caller_5XX_requests_total_value{instance=~\"$instance\"}[1m]))*100/sum(max_over_time(ballerina_http_Caller_requests_total_value{instance=~\"$instance\"}[1m]) - min_over_time(ballerina_http_Caller_requests_total_value{instance=~\"$instance\"}[1m]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_response_time_seconds_value{instance=~\"$instance\",protocol=~\"$protocol\", resource!=\"getMetrics\", resource!=\"balMetric\", resource!=\"jmxMetric\"}",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}},  Service:{{service}}"
    }
   ]
  },
  {
   "title": "Response Time (99% percentile)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_response_time_seconds{instance=~\"$instance\",protocol=~\"$protocol\",quantile=\"0.99\", resource!=\"getMetrics\", resource!=\"balMetric\", resource!=\"jmxMetric\",timeWindow=\"60000\"}",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}, Quantile: {\"0.99\"}, Service:{{service}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ops", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "sum without (http_status_code)(rate(http_requests_total_value{instance=~\"$instance\",protocol=~\"$protocol\",http_method=~\"$http_method\",http_url!=\"/metrics\", http_url!=\"/balMetric\", http_url!=\"/jmxMetric\",service=~\"$service\",resource=~\"$resource\"}[1m]))",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "Response Time (Mean)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_response_time_seconds_mean{instance=~\"$instance\",protocol=~\"$protocol\", resource!=\"getMetrics\", resource!=\"balMetric\", resource!=\"jmxMetric\",timeWindow=\"60000\"}",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}, Service:{{service}}"
    }
   ]
  },
  {
   "title": "Filter Response Mean  Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "Per_Request_Duration_mean",
     "legendFormat": "Category: {{Category}}, Method: {{Method}}, URL: {{ServicePath}}, Instance:{{instance}}, Service: {{Service}}"
    }
   ]
  },
  {
   "title": "Total Filter Response Mean (Summery)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "Request_Duration_Total_mean",
     "legendFormat": "Category: {{Category}}, Instance:{{instance}}"
    }
   ]
  },
  {
   "title": "Top services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,http_requests_total_value{http_url!=\"/metrics\", http_url!=\"/jmxMetrics\"})",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "Slow Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "bottomk(5,http_response_time_seconds_value{http_url!=\"/metrics\", http_url!=\"/jmxMetrics\"})",
     "legendFormat": "Instance: {{instance}}, Protocol: {{protocol}}, Method: {{http_method}}, URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 3, "y": 97 },
   "yaxes": [
    { "format": "short", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "rate(ballerina_http_Caller_1XX_requests_total_value{instance=~\"$instance\", action=~\"respond\"}[1m])",
     "legendFormat": "1xx Informational responses - Instance: {{instance}}"
    },
    {
     "expr": "rate(ballerina_http_Caller_2XX_requests_total_value{instance=~\"$instance\", action=~\"respond\"}[1m])",
     "legendFormat": "2xx Successful responses - Instance: {{instance}}"
    },
    {
     "expr": "rate(ballerina_http_Caller_3XX_requests_total_value{instance=~\"$instance\", action=~\"respond\"}[1m])",
     "legendFormat": "3xx Redirections - Instance: {{instance}}"
    },
    {
     "expr": "rate(ballerina_http_Caller_4XX_requests_total_value{instance=~\"$instance\", action=~\"respond\"}[1m])",
     "legendFormat": "4xx Client errors - Instance: {{instance}}"
    },
    {
     "expr": "rate(ballerina_http_Caller_5XX_requests_total_value{instance=~\"$instance\", action=~\"respond\"}[1m])",
     "legendFormat": "5xx Server errors - Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "MicroGateway HTTP Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 }
  },
  {
   "title": "Requests / min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 107 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( max_over_time({__name__=~\".*HttpClient_requests_total_value\", instance=~\"$instance\", peer_address=~\"$peer_address\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]) - min_over_time({__name__=~\".*HttpClient_requests_total_value\", instance=~\"$instance\", peer_address=~\"$peer_address\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]) ) "
    }
   ]
  },
  {
   "title": "Errors /  min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 107 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( max_over_time(ballerina_http_HttpClient_4XX_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]) - min_over_time(ballerina_http_HttpClient_4XX_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m])+ max_over_time(ballerina_http_HttpClient_5XX_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]) - min_over_time(ballerina_http_HttpClient_5XX_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]) )"
    }
   ]
  },
  {
   "title": "Inprogress Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 107 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ballerina_http_HttpClient_inprogress_requests_value{action=~\"$http_client_action\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Error %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 107 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum( max_over_time(ballerina_http_HttpClient_4XX_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]) - min_over_time(ballerina_http_HttpClient_4XX_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m])+ max_over_time(ballerina_http_HttpClient_5XX_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]) - min_over_time(ballerina_http_HttpClient_5XX_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]))*100/sum( max_over_time(ballerina_http_HttpClient_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]) - min_over_time(ballerina_http_HttpClient_requests_total_value{instance=~\"$instance\", action=~\"$http_client_action\", http_url!=\"/metrics\"}[1m]))\n"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "ops", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "sum without (http_status_code) (rate(ballerina_http_HttpClient_requests_total_value{instance=~\"$instance\",action=~\"$http_client_action\",http_method=~\"$http_method\",peer_address=~\"$peer_address\", http_url!=\"/metrics\"}[1m]))",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Method: {{http_method}}, Peer Address: {{peer_address}}, URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "BackEnd Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "ballerina_http_HttpClient_response_time_seconds_value{instance=~\"$instance\",action=~\"$http_client_action\",http_method=~\"$http_method\",peer_address=~\"$peer_address\", http_url!=\"/metrics\"}",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Method: {{http_method}}, Peer Address: {{peer_address}}, URL: {{http_url}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short", "label": "Requests / sec" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\".*HttpClient_1XX_requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\"}[1m])",
     "legendFormat": "1xx Informational responses - Instance: {{instance}}, Action: {{action}}"
    },
    {
     "expr": "rate({__name__=~\".*HttpClient_2XX_requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\"}[1m])",
     "legendFormat": "2xx Successful responses - Instance: {{instance}}, Action: {{action}}"
    },
    {
     "expr": "rate({__name__=~\".*HttpClient_3XX_requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\"}[1m])",
     "legendFormat": "3xx Redirections - Instance: {{instance}}, Action: {{action}}"
    },
    {
     "expr": "rate({__name__=~\".*HttpClient_4XX_requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\"}[1m])",
     "legendFormat": "4xx Client errors - Instance: {{instance}}, Action: {{action}}"
    },
    {
     "expr": "rate({__name__=~\".*HttpClient_5XX_requests_total_value\", instance=~\"$instance\", action=~\"$http_client_action\"}[1m])",
     "legendFormat": "5xx Server errors - Instance: {{instance}}, Action: {{action}}"
    }
   ]
  },
  {
   "title": "Top remote services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,ballerina_http_HttpClient_requests_total_value{http_url!=\"/metrics\"})",
     "legendFormat": "Instance: {{instance}}, Action: {{action}}, Method: {{http_method}}, Peer Address: {{peer_address}}, URL: {{http_url}}"
    }
   ]
  }
 ]
}