[server]
port = 8080
host = "0.0.0.0"
keyPath = "resources/security/private.key"
certPath = "resources/security/server.pem"
secure = false
readTimeout = 10
writeTimeout = 20
idleTimeout = 60
maxHeaderBytes = 102400

[http]
insecure = false
maxIdleConns = 20
idleConnTimeout = 60

[log]
debug = false