[server]
port = 8080
host = "0.0.0.0"
keyPath = "resources/security/private.key"
certPath = "resources/security/server.pem"
secure = true

[http]
insecure = false
maxIdleConns = 20
idleConnTimeout = 60
