[server]
port = 8080
host = "0.0.0.0"
keyPath = "security/private.key"
certPath = "security/server.pem"
secure = true

[http]
insecure = true
maxIdleConns = 20
idleConnTimeout = 60

[log]
debug = false
