// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/wso2/discovery/subscription/subscription.proto

package subscription

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Subscription data model
type Subscription struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId        string                 `protobuf:"bytes,1,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	PolicyId              string                 `protobuf:"bytes,2,opt,name=policyId,proto3" json:"policyId,omitempty"`
	ApiId                 int32                  `protobuf:"varint,3,opt,name=apiId,proto3" json:"apiId,omitempty"`
	AppId                 int32                  `protobuf:"varint,4,opt,name=appId,proto3" json:"appId,omitempty"`
	SubscriptionState     string                 `protobuf:"bytes,5,opt,name=subscriptionState,proto3" json:"subscriptionState,omitempty"`
	TimeStamp             int64                  `protobuf:"varint,6,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	TenantId              int32                  `protobuf:"varint,7,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	TenantDomain          string                 `protobuf:"bytes,8,opt,name=tenantDomain,proto3" json:"tenantDomain,omitempty"`
	SubscriptionUUID      string                 `protobuf:"bytes,9,opt,name=subscriptionUUID,proto3" json:"subscriptionUUID,omitempty"`
	AppUUID               string                 `protobuf:"bytes,10,opt,name=appUUID,proto3" json:"appUUID,omitempty"`
	ApiUUID               string                 `protobuf:"bytes,11,opt,name=apiUUID,proto3" json:"apiUUID,omitempty"`
	Context               string                 `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
	VersionRange          string                 `protobuf:"bytes,13,opt,name=versionRange,proto3" json:"versionRange,omitempty"`
	BillingCustomerId     string                 `protobuf:"bytes,14,opt,name=billingCustomerId,proto3" json:"billingCustomerId,omitempty"`
	BillingSubscriptionId string                 `protobuf:"bytes,15,opt,name=billingSubscriptionId,proto3" json:"billingSubscriptionId,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_api_proto_wso2_discovery_subscription_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wso2_discovery_subscription_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_proto_wso2_discovery_subscription_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Subscription) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *Subscription) GetApiId() int32 {
	if x != nil {
		return x.ApiId
	}
	return 0
}

func (x *Subscription) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Subscription) GetSubscriptionState() string {
	if x != nil {
		return x.SubscriptionState
	}
	return ""
}

func (x *Subscription) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *Subscription) GetTenantId() int32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Subscription) GetTenantDomain() string {
	if x != nil {
		return x.TenantDomain
	}
	return ""
}

func (x *Subscription) GetSubscriptionUUID() string {
	if x != nil {
		return x.SubscriptionUUID
	}
	return ""
}

func (x *Subscription) GetAppUUID() string {
	if x != nil {
		return x.AppUUID
	}
	return ""
}

func (x *Subscription) GetApiUUID() string {
	if x != nil {
		return x.ApiUUID
	}
	return ""
}

func (x *Subscription) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Subscription) GetVersionRange() string {
	if x != nil {
		return x.VersionRange
	}
	return ""
}

func (x *Subscription) GetBillingCustomerId() string {
	if x != nil {
		return x.BillingCustomerId
	}
	return ""
}

func (x *Subscription) GetBillingSubscriptionId() string {
	if x != nil {
		return x.BillingSubscriptionId
	}
	return ""
}

var File_api_proto_wso2_discovery_subscription_subscription_proto protoreflect.FileDescriptor

const file_api_proto_wso2_discovery_subscription_subscription_proto_rawDesc = "" +
	"\n" +
	"8api/proto/wso2/discovery/subscription/subscription.proto\x12\x1bwso2.discovery.subscription\"\x8c\x04\n" +
	"\fSubscription\x12&\n" +
	"\x0esubscriptionId\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1a\n" +
	"\bpolicyId\x18\x02 \x01(\tR\bpolicyId\x12\x14\n" +
	"\x05apiId\x18\x03 \x01(\x05R\x05apiId\x12\x14\n" +
	"\x05appId\x18\x04 \x01(\x05R\x05appId\x12,\n" +
	"\x11subscriptionState\x18\x05 \x01(\tR\x11subscriptionState\x12\x1c\n" +
	"\ttimeStamp\x18\x06 \x01(\x03R\ttimeStamp\x12\x1a\n" +
	"\btenantId\x18\a \x01(\x05R\btenantId\x12\"\n" +
	"\ftenantDomain\x18\b \x01(\tR\ftenantDomain\x12*\n" +
	"\x10subscriptionUUID\x18\t \x01(\tR\x10subscriptionUUID\x12\x18\n" +
	"\aappUUID\x18\n" +
	" \x01(\tR\aappUUID\x12\x18\n" +
	"\aapiUUID\x18\v \x01(\tR\aapiUUID\x12\x18\n" +
	"\acontext\x18\f \x01(\tR\acontext\x12\"\n" +
	"\fversionRange\x18\r \x01(\tR\fversionRange\x12,\n" +
	"\x11billingCustomerId\x18\x0e \x01(\tR\x11billingCustomerId\x124\n" +
	"\x15billingSubscriptionId\x18\x0f \x01(\tR\x15billingSubscriptionIdB\x96\x01\n" +
	".org.wso2.choreo.connect.discovery.subscriptionB\x11SubscriptionProtoP\x01ZOgithub.com/envoyproxy/go-control-plane/wso2/discovery/subscription;subscriptionb\x06proto3"

var (
	file_api_proto_wso2_discovery_subscription_subscription_proto_rawDescOnce sync.Once
	file_api_proto_wso2_discovery_subscription_subscription_proto_rawDescData []byte
)

func file_api_proto_wso2_discovery_subscription_subscription_proto_rawDescGZIP() []byte {
	file_api_proto_wso2_discovery_subscription_subscription_proto_rawDescOnce.Do(func() {
		file_api_proto_wso2_discovery_subscription_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_wso2_discovery_subscription_subscription_proto_rawDesc), len(file_api_proto_wso2_discovery_subscription_subscription_proto_rawDesc)))
	})
	return file_api_proto_wso2_discovery_subscription_subscription_proto_rawDescData
}

var file_api_proto_wso2_discovery_subscription_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_wso2_discovery_subscription_subscription_proto_goTypes = []any{
	(*Subscription)(nil), // 0: wso2.discovery.subscription.Subscription
}
var file_api_proto_wso2_discovery_subscription_subscription_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_wso2_discovery_subscription_subscription_proto_init() }
func file_api_proto_wso2_discovery_subscription_subscription_proto_init() {
	if File_api_proto_wso2_discovery_subscription_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_wso2_discovery_subscription_subscription_proto_rawDesc), len(file_api_proto_wso2_discovery_subscription_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_wso2_discovery_subscription_subscription_proto_goTypes,
		DependencyIndexes: file_api_proto_wso2_discovery_subscription_subscription_proto_depIdxs,
		MessageInfos:      file_api_proto_wso2_discovery_subscription_subscription_proto_msgTypes,
	}.Build()
	File_api_proto_wso2_discovery_subscription_subscription_proto = out.File
	file_api_proto_wso2_discovery_subscription_subscription_proto_goTypes = nil
	file_api_proto_wso2_discovery_subscription_subscription_proto_depIdxs = nil
}
